[build]
  publish = "/"
  command = "echo 'No build process needed' && exit 0"
  functions = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  port = 8888

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
